### ISSUE TITLE
java.lang.ClassNotFoundException: gate.creole.ontology.BooleanDT

### ISSUE THREAD

**Issue by parvezatsynerzip** [GateNLP/gate-core#31] opened 2018-03-28 05:56 UTC
Hi ,
I am using gate-core 8.4.1 jar and i have Data-property to my classes in ontology and i have to read them , 
          **OInstanceobj.getDatatypePropertyValues(DataProperty);**
So it showing me error : 
java.lang.ClassNotFoundException: gate.creole.ontology.BooleanDT
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1907)
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1750)
	at gate.creole.ontology.impl.sesame.SesameManager.toGateDataType(SesameManager.java:829)
	at gate.creole.ontology.impl.sesame.SesameManager.convertSesameLiteral2Literal(SesameManager.java:763)
	at gate.creole.ontology.impl.sesame.UtilTupleQueryIterator.nextFirst(UtilTupleQueryIterator.java:185)
	at gate.creole.ontology.impl.sesame.OntologyServiceImplSesame.getDatatypePropertyValues(OntologyServiceImplSesame.java:2016)
	at gate.creole.ontology.impl.OInstanceImpl.getDatatypePropertyValues(OInstanceImpl.java:460)
	at output.Output(file:/home/synerzip/GATE_Developer_8.4.1/plugins/ANNIE/japes/output.jape:167)
	at gate.jape.RightHandSide.transduce(RightHandSide.java:344)
**Note : The same jape is working fine from GateUI but giving error from Gate Embeded**

Please Help

**Comment by greenwoodma** [comment] 2018-03-28 09:20
Looking at that stacktrace suggests there is something odd with the way you are using GATE inside a web application. You are getting a ClassNotFound exception from catalina and it doesn't look as if that's tried to call into the GATE classloader at all. Can you provide more details about how you are initialising and calling GATE from within your webapp?

**Comment by greenwoodma** [comment] 2018-05-08 07:54
Closing this as I can't reproduce it and no more details have been provided

**Closed as completed by greenwoodma** 2018-05-08 07:54 UTC
