### ISSUE TITLE
Ready made ANNIE application does not use the ANNIE plugin version that got loaded

### ISSUE THREAD

**Issue by johann-petrak** [GateNLP/gate-core#108] opened 2020-01-14 14:42 UTC
I am running GATE Developer 9.0, in the plugin manager I load ANNIE version 8.6 then I 
choose Applications - Ready Made Applications - ANNIE - ANNIE.

I get an exception uk.ac.gate.plugins:annie:jar:creole:9.0-SNAPSHOT in gate-repo (http://repo.gate.ac.uk/content/groups/public/)

This is very surprising behaviour.

Would the 9.0-SNAPSHOT version of ANNIE already exist, I would probably have never noticed that the version that gets loaded is completely different from why I deliberately loaded just before. 

I assume this happens because ANNIE is already somehow special and already in the menu even before the plugin gets loaded (why?) but even then this should probably only use the hard-coded ANNIE version as a fallback if ANNIE has not already been loaded.

**Comment by ianroberts** [comment] 2020-01-14 14:50
The ANNIE "ready-made application" menu item is a special one that is hard coded to load an ANNIE app whose version matches the running GATE, it isn't provided by the plugin like other entries in that menu.  This is so there's still a one button way to load the ANNIE app even before you've loaded the plugin.

I agree it would be nice if this could be slightly more intelligent about the version, and if there is already one ANNIE plugin version loaded then use that one.  Which version it should use if there is more than one version of the ANNIE plugin currently loaded is more complex, I guess it has to be the one that was loaded first (which may or may not be the most up to date version) to be sure that the classes and the resource files match.

**Comment by greenwoodma** [comment] 2020-01-14 14:52
Closing as duplicate of #105

**Closed as completed by greenwoodma** 2020-01-14 14:52 UTC

**Comment by johann-petrak** [comment] 2020-01-14 14:54
I have seen #105 but the description would not have helped me to figure out that it is about this issue. I thougth it is simply about how to version-number the plugin independently from core.

**Comment by greenwoodma** [comment] 2020-01-14 15:33
it is, but the only problem with the plugin and gate-core being different versions is that the ANNIE (and OpenNLP) menu items no longer work.

**Comment by greenwoodma** [comment] 2020-01-14 15:40
> it is, but the only problem with the plugin and gate-core being different versions is that the ANNIE (and OpenNLP) menu items no longer work.

although I admit I could have done a better job of describing #105.... like actually adding a description, sorry!
